/**
 * Canonical transaction category taxonomy — the single backend-owned source of
 * truth for the category contract. Stored values are the lowercase `key`s; the
 * `label`s are display-ready names served to clients so a picker never drifts
 * from what the write endpoints accept. Keep this list in sync with the paired
 * presentation map in `mintly-app/constants/categories.ts`.
 */
export interface SupportedCategory {
  /** Stored, lowercase contract value. */
  key: string;
  /** Human-readable display name. */
  label: string;
}

export const SUPPORTED_TRANSACTION_CATEGORIES: readonly SupportedCategory[] = [
  { key: 'food', label: 'Food & Dining' },
  { key: 'groceries', label: 'Groceries' },
  { key: 'transport', label: 'Transport' },
  { key: 'travel', label: 'Travel' },
  { key: 'shopping', label: 'Shopping' },
  { key: 'bills', label: 'Bills & Utilities' },
  { key: 'housing', label: 'Housing & Rent' },
  { key: 'health', label: 'Health' },
  { key: 'entertainment', label: 'Entertainment' },
  { key: 'subscriptions', label: 'Subscriptions' },
  { key: 'education', label: 'Education' },
  { key: 'personal', label: 'Personal' },
  { key: 'income', label: 'Income' },
  { key: 'transfer', label: 'Transfer' },
  { key: 'other', label: 'Other' },
] as const;

export const SUPPORTED_CATEGORY_KEYS: readonly string[] =
  SUPPORTED_TRANSACTION_CATEGORIES.map((c) => c.key);

/**
 * Spanish display labels, keyed by category key. Kept in sync with the frontend
 * `categories.*` i18n catalog. Used for backend-generated localized copy (e.g.
 * alerts); the English labels live on {@link SUPPORTED_TRANSACTION_CATEGORIES}.
 */
const CATEGORY_LABELS_ES: Record<string, string> = {
  food: 'Comida y restaurantes',
  groceries: 'Supermercado',
  transport: 'Transporte',
  travel: 'Viajes',
  shopping: 'Compras',
  bills: 'Facturas y servicios',
  housing: 'Vivienda y alquiler',
  health: 'Salud',
  entertainment: 'Entretenimiento',
  subscriptions: 'Suscripciones',
  education: 'Educación',
  personal: 'Personal',
  income: 'Ingresos',
  transfer: 'Transferencia',
  other: 'Otros',
};

/**
 * Display label for a category key in the given language. Case-insensitive on
 * the key (so a stored `"Other"` resolves), Spanish where available, English
 * otherwise, and the raw value as a last resort for unknown categories.
 */
export function localizedCategoryLabel(key: string, language: 'en' | 'es'): string {
  const k = (key ?? '').toLowerCase();
  if (language === 'es' && CATEGORY_LABELS_ES[k]) return CATEGORY_LABELS_ES[k];
  const found = SUPPORTED_TRANSACTION_CATEGORIES.find((c) => c.key === k);
  return found?.label ?? key;
}

/** True when `value` is one of the canonical category keys. */
export function isTransactionCategoryKey(value: unknown): value is string {
  return typeof value === 'string' && SUPPORTED_CATEGORY_KEYS.includes(value);
}

export const TRANSACTION_TYPES = ['debit', 'credit'] as const;
export type TransactionType = (typeof TRANSACTION_TYPES)[number];

/** True when `value` is a valid transaction direction. */
export function isTransactionType(value: unknown): value is TransactionType {
  return value === 'debit' || value === 'credit';
}

/**
 * How a transaction entered the system. `email`/`sms` are ingested by the
 * pipeline; `manual` is a user-entered record (e.g. cash spending) and `chat`
 * is created through the assistant; `recurring` is generated by the monthly
 * recurring-transactions job. Manual entry defaults to `manual`.
 */
export const TRANSACTION_SOURCES = ['email', 'sms', 'manual', 'chat', 'recurring'] as const;
export type TransactionSource = (typeof TRANSACTION_SOURCES)[number];

/** True when `value` is a recognized transaction source. */
export function isTransactionSource(value: unknown): value is TransactionSource {
  return (
    typeof value === 'string' &&
    (TRANSACTION_SOURCES as readonly string[]).includes(value)
  );
}
